// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  carousel: dynamic(() => import("./Carousel")),
  featured_work: dynamic(() => import("./FeaturedWork")),
  home_hero: dynamic(() => import("./HomeHero")),
  image_block: dynamic(() => import("./Image")),
  rich_text: dynamic(() => import("./RichText")),
  text_block: dynamic(() => import("./Text")),
  video: dynamic(() => import("./Video")),
};
