// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  case_study_hero: dynamic(() => import("./CaseStudyHero")),
  featured_work: dynamic(() => import("./FeaturedWork")),
  home_hero: dynamic(() => import("./HomeHero")),
  image_block: dynamic(() => import("./Image")),
  rich_text: dynamic(() => import("./RichText")),
  text_block: dynamic(() => import("./Text")),
};
